--Item table format:
--{thing selling, price (in gold ingots), chance that it won't appear in the trader's inventory}

--Item table format:
--{thing selling, price (in gold coins), chance that it won't appear in the trader's inventory}

lottmobs.dwarf = {
	items = {
		{"projectile:bow 1", "simplecoins:coins 67", 8},
		{"3d_armor:chestplate_steel 1", "simplecoins:coins 240", 50},
		{"shields:bronze_shield 1", "simplecoins:coins 152", 50},
		{"default:steel_ingot 99", "simplecoins:coins 500", 12},
		{"tinkering:silver_sword 1", "simplecoins:coins 125", 10},
		{"default:bronze_ingot 25", "simplecoins:coins 250", 15},
		{"default:zinc_lump 5", "simplecoins:coins 7", 15},
		{"default:tin_lump 5", "simplecoins:coins 15", 15},
		{"default:nickel_lump 5", "simplecoins:coins 30", 15},
		{"default:copper_lump 5", "simplecoins:coins 60", 15},
		{"default:coal_lump 32", "simplecoins:coins 180", 15},
		{"default:iron_lump 1", "simplecoins:coins 120", 20},
		{"default:titanium_lump 5", "simplecoins:coins 742", 20},
		{"default:ruby 1", "simplecoins:coins 45", 20},
		{"default:sapphire 1", "simplecoins:coins 45", 20},
		{"default:opal 1", "simplecoins:coins 90", 20},
		{"default:diamond 1", "simplecoins:coins 90", 20},
		{"default:fopal 1", "simplecoins:coins 180", 30},
		{"default:emerald 1", "simplecoins:coins 120", 30},
		{"default:btopaz 3", "simplecoins:coins 135", 30},
		{"default:axe_csteel 1", "simplecoins:coins 280", 30},
		{"default:obsidian 2", "simplecoins:coins 75", 30},
		{"default:gneiss 3", "simplecoins:coins 67", 25},
		{"default:granite 10", "simplecoins:coins 37", 10},
		{"default:axe_steel 1", "simplecoins:coins 180", 10},
		{"tinkering:silver_axe 1", "simplecoins:coins 75", 18},
		{"default:granitebrick 99", "simplecoins:coins 180", 12},
		{"default:basaltbrick 99", "simplecoins:coins 210", 17},
		{"default:stonebrick 99", "simplecoins:coins 150", 14},
		{"default:sstonebrick 99", "simplecoins:coins 240", 17},
	},
	items_race = {
		{"projectile:bow 1", "simplecoins:coins 37", 8},
		{"3d_armor:chestplate_steel 1", "simplecoins:coins 120", 50},
		{"shields:bronze_shield 1", "simplecoins:coins 82", 50},
		{"default:steel_ingot 99", "simplecoins:coins 187", 12},
		{"tinkering:silver_sword 1", "simplecoins:coins 52", 10},
		{"default:bronze_ingot 25", "simplecoins:coins 60", 15},
		{"default:zinc_lump 8", "simplecoins:coins 7", 15},
		{"default:tin_lump 8", "simplecoins:coins 15", 15},
		{"default:nickel_lump 8", "simplecoins:coins 22", 15},
		{"default:copper_lump 16", "simplecoins:coins 60", 15},
		{"default:coal_lump 24", "simplecoins:coins 60", 15},
		{"default:iron_lump 5", "simplecoins:coins 120", 20},
		{"default:titanium_lump 5", "simplecoins:coins 300", 20},
		{"default:ruby 3", "simplecoins:coins 45", 20},
		{"default:sapphire 3", "simplecoins:coins 45", 20},
		{"default:opal 1", "simplecoins:coins 52", 20},
		{"default:diamond 1", "simplecoins:coins 52", 20},
		{"default:fopal 1", "simplecoins:coins 90", 30},
		{"default:emerald 1", "simplecoins:coins 90", 30},
		{"default:btopaz 3", "simplecoins:coins 45", 30},
		{"default:axe_csteel 1", "simplecoins:coins 90", 30},
		{"default:obsidian 3", "simplecoins:coins 60", 30},
		{"default:gneiss 3", "simplecoins:coins 60", 25},
		{"default:granite 12", "simplecoins:coins 30", 10},
		{"default:axe_steel 1", "simplecoins:coins 60", 10},
		{"tinkering:silver_axe 1", "simplecoins:coins 37", 18},
		{"default:granitebrick 99", "simplecoins:coins 90", 12},
		{"default:basaltbrick 99", "simplecoins:coins 105", 17},
		{"default:stonebrick 99", "simplecoins:coins 75", 14},
		{"default:sstonebrick 99", "simplecoins:coins 120", 17},
	},
	names = {
    "Azaghâl", "Balbrin", "Farin", "Flói", "Frerin",
    "Grór", "Lóni", "Náli", "Narvi", "Telchar", "Thion", "Thorin",
    "Bifur", "Balin", "Bofur", "Dori", "Nori",
    "Ori", "Gamil", "Grendel Duvving", "Mr. Duvving", "Oren",
    "Brelan-Bru", "Brelan-Ru", "Bahla", "Mr. Garnetglassed", "Mr. Garnetglassed Senior",
    "Garnetglassed, son of Garnetglassed", "Thrane", "Angil", "Angilad", 
    "Angilas", "Angiras", "Thule", "Tula", "Thorwyn", "Thorn, Son of Thorwynn", 
    "Thorwynn", "Anigellum, Champion of Novus", "Dodok Kullistem", "Sarvoresh",
    "Sarvesh", "Shem Zutthanedok", "Hush", "Potski", "Squie", "Angellum", "Vellaris",
    "Sothol-Sim", "Dhudush-Crock", "Durzogar Stone-Fist", "Skiv", "Thrall of Sorak",
    "Mugrak Stonearm", "Kazran Fireforge", "Drokil Earthsunder", "Thalrak Blackbeard",
    "Vekrim Irongut", "Bramil Deepdelver", "Kromnir Anvilfist", "Thrain Goldvein",
    "Gundrek Thunderaxe", "Rurik Ironfury", "Rorik of of Rorikshire", "Kaldor Stonebreaker", "Tharnim Forgeheart",
    "Mordrin Darkhammer", "Skarn Stonehelm", "Thorek Frostbeard", "Ragnir Emberstrike",
    "Baldur Oreblade", "Korgrim Flintshield", "Thrain Firebelly", "Brogar Bloodhammer", "Thorn"
	},

	messages = {
    "We have many treasures, and for the right price we might be willing to part with them...",
    "Don't even think of stealing our treasure... If you do, heads shall roll.",
    "What are you doing here? What do you want from us?",
    "Be careful when you enter our homes, a fall from the ladder could well prove deadly.",
    "If you want to mine, do so. There's plenty of iron to go around!",
    "If you venture deep underground, beware! The monsters there are very powerful, and kill the unprepared instantly.",
    "Mines of Nun, where all our riches are! Mines of Nun, where our greed led to destruction.",
    "We can’t bring a troll to the fire, but we can bring the fire to the troll.",
    "Never turn down an ale, who knows if it may be your last...",
    "Guard your life, guard your gold, guard your beard. In that order.",
    "Wherever there are elves, there are lies.",
    "The Humans have a saying. The nail that sticks out gets hammered. We have a saying too. Shoddy work! Not a single nail should be sticking out.",
    "You can kill a dwarf, but you can never vanquish one.",
    "It is easy to fool a goblin, but even easier to kill one.",
    "The best place to hide something precious is in your beard.",
    "Evil breeds in the guts of the lazy.",
    "The age of Sorak has passed, yet the age of Acerak reigns supreme... One evil for another, I suppose.",
    "The stones will sing if you let them.",
    "Drinking contests with humans are unbearable. They drink, they collapse, and we have to drag them back to their homes. The next day they never remember losing.",
    "A spear is not a dwarven weapon, but it will kill all the same.",
    "The Mithril beneath Nune's mountains calls to us... but at what cost?",
    "These mountains may be harsh, but they are our home. No man or beast can take that from us.",
    "Our forges burn hot, but our hearts burn hotter. What do you need forged today?",
    "In Nune, gold flows like water, but it’s Mithril that truly has value.",
    "We dig deep not just for riches, but for the heart of the earth itself.",
    "The forests of Nune may hide treasures, but beware the dangers within.",
    "You think a dragon is tough? Try the wrath of a dwarf scorned!",
    "Our hammers and anvils sing with the rhythm of the earth. What tune does your coin play?",
    "The humans of Nune may build cities, but our halls are older and stronger.",
    "These hills have eyes... Dwarven eyes. So don't try anything funny."
}

}

lottmobs.elf = {
	items = {
		{"default:tree 10", "simplecoins:coins 25", 5},
		{"default:granite 4", "simplecoins:coins 125", 17},
		{"moretorches:pinewoodtorch 10", "simplecoins:coins 120", 15},
		{"castle:crossbow 1", "simplecoins:coins 187", 20},
		{"castle:bolt 10", "simplecoins:coins 60", 20},
		{"tinkering:silver_axe 1", "simplecoins:coins 135", 14},
		{"default:sword_csteel 1", "simplecoins:coins 172", 25},
		{"x_farming:corn 10", "simplecoins:coins 15", 22},
		{"x_farming:strawberry 12", "simplecoins:coins 22", 14},
		{"dynamic_trees:sakura_tree_sapling 3", "simplecoins:coins 15", 17},
		{"default:goldblock " .. math.random(8, 10), "lottores:pearl 67", 25},
	},
	items_race = {
		{"default:tree 10", "simplecoins:coins 20", 5},
		{"default:granite 4", "simplecoins:coins 85", 17},
		{"moretorches:pinewoodtorch 10", "simplecoins:coins 60", 15},
		{"spears:spear_steel 1", "simplecoins:coins 187", 20},
		{"castle:bolt 10", "simplecoins:coins 30", 20},
		{"castle:crossbow 1", "simplecoins:coins 107", 20},
		{"tinkering:silver_axe 1", "simplecoins:coins 135", 14},
		{"default:sword_csteel 1", "simplecoins:coins 172", 25},
		{"x_farming:corn 10", "simplecoins:coins 15", 22},
		{"x_farming:strawberry 12", "simplecoins:coins 22", 14},
		{"dynamic_trees:sakura_tree_sapling 3", "simplecoins:coins 15", 17},
		{"default:goldblock " .. math.random(8, 10), "default:mithril_lump 7", 25},
	},
	names = {
    "Annael", "Anairë", "Curufin", "Erestor", "Gwindor", "Irimë",
    "Oropher", "Maglor", "Quennar", "Rúmil", "Orgof", "Voronwë",
    "Hinnoron", "Malton", "Bornor", "Landaer", "Nardchanar",
    "Delebon", "Gollorchanar", "Noron", "Preston", "Radhril",
    "Mistriel", "Ganis", "Mithes", "Loboril",
    "Elianor", "Lothrin", "Finaris", "Altherin", "Thalnor", "Eldorin",
    "Isilwen", "Calanon", "Rhiannon", "Thalindor", "Elarian", "Lytherion",
    "Thrandor", "Eldamar", "Ithilrin", "Maerion", "Eredhel", "Lunithor",
    "Rilven", "Ellisar", "Valandor", "Sylanthir", "Aeloria", "Mythrandir",
    "Arandor", "Fenris", "Islador", "Lorien", "Thranduil", "Elorion"
	},
	messages = {
    "Welcome to our lovely forest home, weary traveler. Refresh yourself here.",
    "Sorak grows in power. Shall we be able to vanquish him again?",
    "We are a peace-loving people, but if we are angered, our wrath is terrible!",
    "Rest among us and prepare yourself, for war is imminent.",
    "If you wish to buy goods from us, there are certain traders who wander our land.",
    "Beware! Our society, and all societies, are on the edge of a knife blade - one false move and all will end, and Sorak will rule supreme.",
    "Êl síla erin lû e-govaned vîn.",
    "It is perilous to study too deeply the arts of the Enemy, for good or for ill. But such falls and betrayals, alas, have happened before.",
    "Do not meddle in the affairs of Wizards, for they are subtle and quick to anger.",
    "The praise of the praiseworthy is above all rewards.",
    "The old that is strong does not wither, deep roots are not reached by the frost.",
    "I will not say 'do not weep,' for not all tears are an evil.",
    "For even the very wise cannot see all ends.",
    "Faithless is he who says farewell when the road darkens.",
    "Aa' lasser en lle coia orn n' omenta gurtha.",
    "Sweet water and light laughter till next we meet.",
    "Aa' menealle nauva ar' malta.",
    "May the wind fill your sails.",
    "Do not scorn pity that is the gift of a gentle heart, Éowyn!",
    "Someone else always has to carry on the story.",
    "The forests of Nune whisper secrets to those who listen.",
    "The ancient trees here have seen more than any man or dwarf. Respect them.",
    "Our arrows fly true, guided by the spirits of Nune's woods.",
    "The sea to the south calls to us, but the land of Nune holds us fast.",
    "Mithril may be precious, but the knowledge of the earth is beyond value.",
    "Not all who wander are lost, especially in the forests of Nune.",
    "Beware the deep places of the world, for Nune hides many secrets.",
    "Our songs carry the history of Nune, from the mountains to the sea.",
    "In Nune, the stars shine brighter, and the dangers grow darker.",
    "The harmony of nature is fragile. Tread lightly, traveler."
}
}

lottmobs.human = {
	items = {
		{"default:sandstone 40", "simplecoins:coins 75", 12},
		{"boats:boat 1", "simplecoins:coins 40", 14},
		{"shields:shield_bronze 1", "simplecoins:coins 150", 20},
		{"farming:bread 12", "simplecoins:coins 50", 5},
		{"default:limestonebrick 35", "simplecoins:coins 90", 10},
		{"default:desert_stone 30", "simplecoins:coins 60", 12},
		{"default:torch 99", "simplecoins:coins 99", 8},
		{"3d_armor:chestplate_bronze 1", "simplecoins:coins 225", 30},
		{"3d_armor:boots_bronze 1", "simplecoins:coins 90", 18},
		{"doors:door_wood 6", "simplecoins:coins 15", 18},
		{"default:limestone 99", "simplecoins:coins 247", 18},
		{"3d_armor:helmet_bronze 1", "simplecoins:coins 150", 24},
		{"x_farming:silt_loam_brick_block 30", "simplecoins:coins 75", 17},
		{"3d_armor:leggings_bronze 1", "simplecoins:coins 187", 34},
	},
	items_race = {
		{"default:sandstone 40", "simplecoins:coins 75", 12},
		{"boats:boat 1", "simplecoins:coins 17", 14},
		{"shields:shield_bronze 1", "simplecoins:coins 120", 20},
		{"farming:bread 12", "simplecoins:coins 36", 5},
		{"default:limestonebrick 35", "simplecoins:coins 80", 10},
		{"default:desert_stone 30", "simplecoins:coins 40", 12},
		{"default:torch 99", "simplecoins:coins 30", 8},
		{"3d_armor:chestplate_bronze 1", "simplecoins:coins 125", 30},
		{"3d_armor:boots_bronze 1", "simplecoins:coins 80", 18},
		{"doors:door_wood 6", "simplecoins:coins 15", 18},
		{"default:limestone 99", "simplecoins:coins 207", 18},
		{"3d_armor:helmet_bronze 1", "simplecoins:coins 80", 24},
		{"x_farming:silt_loam_brick_block 30", "simplecoins:coins 45", 17},
		{"3d_armor:leggings_bronze 1", "simplecoins:coins 167", 34},
	},
	names = {
		"Aratan", "Arvegil", "Belegorn", "Celepharn", "Dúnhere", "Elatan",
		"Gilraen", "Írimon", "Minardil", "Oromendil", "Tarcil", "Vorondil",
		"Eldrin", "Roderic", "Cedric", "Alistair", "Gareth", "Lysander",
		"Tristan", "Eamon", "Theron", "Viggo", "Wulfric", "Roderick",
		"Edric", "Baldric", "Aldwin", "Leofric", "Garrick", "Rowan",
		"Caius", "Darian", "Orin", "Caden", "Alaric", "Duncan",
		"Jareth", "Brynden", "Corwin", "Eldon", "Lucian", "Merric",
		"Jerric", "Aeric", "Baeric", "Cedric", "Derik", "Erik", "Fering",
		"Gerrick", "Harric", "Iric", "Kerric", "Kerric, The Cleric",
		"Lairick", "Nerrick", "Orik", "Perric", "Qerric", "Rick",
		"Serrick", "Terrick", "Tarek", "Terik", "Urik", "Uruk", 
		"Verik", "Werric", "Xeric", "Yerick", "Yarel", "Zerik", "Zerrick",
		"Valen", "Thorn", "Ragnar", "Haleth", "Theoden", "Brandir"
	},
	messages = {
    "War comes swiftly... We are preparing, but are we doing enough?",
    "The noble race of man rises in the world! Even the dwarves are starting to show interest in some of our goods.",
    "Are you willing to fight with us? We have much to lose, but much to gain also! We must rally together.",
    "Don't listen to those who say that all this talk of war will come to nothing, for we are at war now.",
    "We suffer raids from orcs, and other evil things, yet we do nothing! We must act, and act with force!",
    "Life here is far from normal. We wish for peace, yet the only way we can get peace is through war...",
    "The markets of Nune are bustling. What are you looking for today?",
    "Mithril is the lifeblood of Nune, but it comes at a price. Are you willing to pay it?",
    "The seas to the south of Nune are full of mysteries. Care to trade tales?",
    "We humans are adaptable. In the jungles, forests, and prairies of Nune, we've learned to thrive.",
    "Beware the night, traveler. Nune's lands are home to more than just beasts.",
    "Our swords are forged with the strength of Nune's mountains. Will you wield one?",
    "Trade is the heart of Nune's cities. What do you have to offer?",
    "The barbarians of the north may be fierce, but we’ve learned to hold our ground.",
    "Gold can buy much, but in Nune, knowledge is the true currency.",
    "Nune’s prairies are vast, but nowhere is safe from the storms that gather.",
    "Our cities may be young, but they stand strong against the tides of war.",
    "The ghosts of Nune’s past still walk these lands. What stories do you bring?",
    "Our people are united by more than just trade. The bonds of Nune run deep.",
    "The sea to the south holds many treasures, but only the brave dare seek them."
}
}

lottmobs.mung_trader = {
	items = {
		{"default:trout_item 1", "simplecoins:coins 3", 10},
		{"default:trout_item 5", "simplecoins:coins 15", 10},
		{"default:trout_item 10", "simplecoins:coins 30", 10},
		{"default:trout_item 12", "simplecoins:coins 35", 10},
		{"default:clay_brick 10", "simplecoins:coins 20", 15},
		{"default:wood 5", "simplecoins:coins 10", 12},
		{"spears:spear_wood 1", "simplecoins:coins 10", 12},
		{"spears:spear_stone 1", "simplecoins:coins 15", 12},
		{"default:flint 3", "simplecoins:coins 7", 20},
		{"default:stick 10", "simplecoins:coins 5", 10},
		{"default:stone 10", "simplecoins:coins 12", 15},
		{"default:mese_crystal_fragment 1", "simplecoins:coins 50", 5},
		{"default:clay 5", "simplecoins:coins 15", 10},
		{"default:dry_shrub 1", "simplecoins:coins 2", 20},
		{"default:pine_needles 10", "simplecoins:coins 5", 15},
		{"default:junglegrass 5", "simplecoins:coins 7", 15},
		{"default:torch 5", "simplecoins:coins 8", 12},
		{"default:cobble 20", "simplecoins:coins 18", 10},
		{"default:obsidian 2", "simplecoins:coins 35", 12},
		{"default:papyrus 3", "simplecoins:coins 10", 18},
		{"bones:bones 3", "simplecoins:coins 12", 20},
		{"default:limestonebrick 99", "simplecoins:coins 40", 15},
		{"default:granitebrick 99", "simplecoins:coins 50", 15},
		{"default:onyxbrick 99", "simplecoins:coins 55", 15},
		{"default:scobblebrick 99", "simplecoins:coins 35", 15},
		{"default:prick 99", "simplecoins:coins 25", 15},
		{"default:mud_brick 99", "simplecoins:coins 45", 20},  -- Common 
		{"default:mud_brick 99", "simplecoins:coins 65", 20},  -- Common 
		{"default:mud_brick 99", "simplecoins:coins 15", 20},  -- Common 
		{"default:mud_brick 99", "simplecoins:coins 25", 20},  -- Common 
		{"default:mud_brick 99", "simplecoins:coins 12", 20},  -- Common trade
		{"default:slatebrick 99", "simplecoins:coins 45", 15},
		{"default:shobblebrick 99", "simplecoins:coins 35", 15},
		{"default:marblebrick 99", "simplecoins:coins 60", 15},
		{"default:schistbrick 99", "simplecoins:coins 50", 15},
		{"default:trout_item 10", "default:ruby 1", 10},
		{"default:trout_item 12", "default:opal 1", 10},
		{"default:wood 5", "default:trout_item 7", 12},
		{"default:wood 5", "default:fish_item 12", 12},
		{"spears:spear_wood 1", "simplecoins:coins 7", 12},
		{"spears:spear_flint 1", "projectile:rock 4", 12},
		{"spears:spear_wood 1", "projectile:rock 12", 12},
		{"default:stick 10", "default:trout_item 2", 10},
		{"default:mese_crystal_fragment 1", "default:ruby 1", 5},
		{"default:clay 5", "default:fish_item 12", 10},
		{"default:torch 5", "group:stone 5", 12},
		{"default:cobble 20", "default:emerald 1", 10},
		{"bones:bones 3", "simplecoins:coins 8", 20},
		{"bones:bones 3", "default:fish_item 18", 20},
		{"bones:bones 3", "default:trout_item 8", 20},
		{"default:prick 99", "default:fish_item 20", 15},
		{"default:mud_brick 99", "default:trout_item 10", 20},
	},
	items_race = {
		{"default:trout_item 1", "simplecoins:coins 2", 10},
		{"default:trout_item 5", "simplecoins:coins 10", 10},
		{"default:trout_item 10", "simplecoins:coins 25", 10},
		{"default:trout_item 12", "simplecoins:coins 30", 10},
		{"default:trout_item 10", "default:ruby 1", 10},
		{"default:trout_item 12", "default:opal 1", 10},
		{"default:clay_brick 10", "simplecoins:coins 15", 15},
		{"default:wood 5", "simplecoins:coins 7", 12},
		{"default:wood 5", "default:trout_item 7", 12},
		{"default:wood 5", "default:fish_item 12", 12},
		{"spears:spear_wood 1", "simplecoins:coins 7", 12},
		{"spears:spear_flint 1", "projectile:rock 4", 12},
		{"spears:spear_wood 1", "projectile:rock 12", 12},
		{"spears:spear_stone 1", "simplecoins:coins 12", 12},
		{"default:flint 3", "simplecoins:coins 5", 20},
		{"default:stick 10", "simplecoins:coins 3", 10},
		{"default:stick 10", "default:trout_item 2", 10},
		{"default:stone 10", "simplecoins:coins 10", 15},
		{"default:mese_crystal_fragment 1", "default:ruby 1", 5},
		{"default:clay 5", "default:fish_item 12", 10},
		{"default:dry_shrub 1", "simplecoins:coins 1", 20},
		{"default:pine_needles 10", "simplecoins:coins 3", 15},
		{"default:junglegrass 5", "simplecoins:coins 5", 15},
		{"default:torch 5", "simplecoins:coins 5", 12},
		{"default:torch 5", "group:stone 5", 12},
		{"default:cobble 20", "default:emerald 1", 10},
		{"default:obsidian 2", "simplecoins:coins 25", 12},
		{"default:papyrus 3", "simplecoins:coins 7", 18},
		{"bones:bones 3", "simplecoins:coins 8", 20},
		{"bones:bones 3", "default:fish_item 18", 20},
		{"bones:bones 3", "default:trout_item 8", 20},
		{"default:limestonebrick 99", "simplecoins:coins 30", 15},
		{"default:granitebrick 99", "simplecoins:coins 40", 15},
		{"default:onyxbrick 99", "simplecoins:coins 45", 15},
		{"default:scobblebrick 99", "simplecoins:coins 30", 15},
		{"default:prick 99", "simplecoins:coins 20", 15},
		{"default:prick 99", "default:fish_item 20", 15},
		{"default:mud_brick 99", "default:trout_item 10", 20},  
		{"default:mud_brick 99", "simplecoins:coins 20", 20},  -- Common 
		{"default:mud_brick 99", "simplecoins:coins 20", 20},  -- Common 
		{"default:mud_brick 99", "simplecoins:coins 20", 20},  -- Common 
		{"default:mud_brick 99", "simplecoins:coins 20", 20},  -- Common 
		{"default:mud_brick 99", "simplecoins:coins 20", 20},  -- Common trade
		{"default:slatebrick 99", "simplecoins:coins 35", 15},
		{"default:shobblebrick 99", "simplecoins:coins 30", 15},
		{"default:marblebrick 99", "simplecoins:coins 50", 15},
		{"default:schistbrick 99", "simplecoins:coins 40", 15},
	},
	names = {
    -- 1-Syllable Names
    "Brak", "Zog", "Krak", "Thak", "Rok", "Grim", "Drak", "Korn", "Frog",
    "Tug", "Grok", "Jarn", "Duk", "Nok", "Vik", "Jok", "Krum", "Bork", 
    "Hrok", "Zan", "Gor", "Nub", "Rog", "Bam", "Vug", "Rag", "Truk", 
    "Kov", "Zam", "Du", "Fru", "Tor", "Gur", "Vok", "Gid", "Jup", "Hik", 
    "Vrag", "Hark", "Drok", "Throg", "Mungar", "Thrudak", "Gorok", "Zorok", "Brakkor", "Kromak", "Norgak", 
    "Vrogor", "Tarkon", "Murgar", "Hakkor", "Skragar", "Thogar", "Drokkar", 
    "Frakor", "Grakar", "Vrakor", "Throgor", "Kragar", "Brorgak", "Zogar", 
    "Mundar", "Rrokor", "Grokon", "Larnok", "Malkor", "Tarnak", "Hrokor", 
    "Jornak", "Vorgar", "Rukkus", "Gorak", "Dudu", "Zorakar", "Lugorak", "Nokarok", "Mungarok", "Gorakar", "Drakor", 
    "Zugrak", "Vrogoron", "Tarkoron", "Murgaron", "Hakkoron", "Skragaron", 
    "Thogaron", "Drokkaron", "Frakaron", "Grakaron", "Zorakaron", 
    "Vrakoron", "Throgoron", "Kragarok", "Brorgakon", "Zogarok", 
    "Mundaron", "Rrokoron", "Grokonon", "Larnokon", "Malkoron", 
    "Tarnakon", "Hrokoron", "Jornakon", "Lugorakon", "Nokaronok", 
    "Dududu", "Dudududu",
},
	messages = {
    "Welcome, stranger. Mung have what you need, maybe.",
    "Trade with Mung, good deal for you, good deal for Mung.",
    "Mung find good things in forest, want to trade?",
    "Careful, Nune is dangerous, but Mung strong. You strong too?",
    "Clay, sticks, stones... Mung trade all for shiny coins.",
    "Mung catch big fish, good trade! You hungry?",
    "Mung make strong bricks, good for building. You build?",
    "Mung find shiny rock, very special. You want?",
    "Mung not just find, Mung make too! Strong and useful things.",
    "Wood, stone, bones... Mung have many things from Nune.",
    "Mung trade whatever Mung find. Mung good trader.",
    "Look around, see if Mung have what you want.",
    "Mung like good trade, make Mung happy. You happy too.",
    "Be careful in Nune. Mung know, Mung see many things.",
    "Fish from river, stones from mountain, all good trade.",
    "Mung find things in Nune. Trade with Mung, yes?",
    "Mung know where to find rare things. You interested?",
    "Mung not afraid of monsters, Mung deal with them.",
    "Shiny coins make Mung happy, what about you?",
    "You have special item? Mung willing to trade good things.",
    "Mung strong, but Mung smarter with trades.",
    "Mung travel far to bring best goods. You buy?",
    "Nune full of danger, but Mung knows safe paths.",
    "Mung like to trade, but Mung also like stories. You have story?",
    "Mung see many travelers, but you seem different. Why?",
    "Mung have secret deals for good traders. You want secret?",
    "Mung always looking for new things. You find something new?",
    "Mung know where to find best stones. You need stones?",
    "Mung can teach you many things about Nune. You listen?",
    "Mung find best fish in river. You try?",
    "Mung make strong tools, good for fighting. You need tools?",
    "Mung hear trolls near volcanoes. You careful there, yes?",
    "Deep caves hold treasures, but also danger. Mung trade safe things.",
    "Jungle has rare herbs. Mung have them if you want.",
    "Volcanoes make land strong. Mung bricks strong too!",
    "Frozen mountains hard to live in. Mung can help you stay warm.",
    "Dragons fly over Nune. Mung stay low and trade quietly.",
    "Mung see big monsters, but Mung not scared. You need defense?",
    "Undead knights walk at night. Mung trade fire for safety.",
    "Mung know where dinosaurs roam. Mung can guide you, for a price.",
    "Mung trade camels in Endless Desert. You need ride?",
    "Goblins tricky. Mung know how to deal with them.",
    "Elves in Nune not friendly. Mung better friend, yes?",
    "Mung know Dwarves make good tools. Mung trade their things.",
    "Pigmen rough, but Mung tougher. Mung trade smart.",
    "Cyclops strong, but Mung strong too. Mung have powerful items.",
    "Ettin double trouble, but Mung not worried. Mung trade safe.",
    "Werewolves hunt at night. Mung have silver, you want?",
    "Vampires need special things. Mung know what they want.",
}

}

minetest.override_item("default:dirt", {
    after_dig_node = function(pos, oldnode, oldmetadata, digger)
        -- Reset the node to air after digging to prevent respawn
        minetest.set_node(pos, {name = "air"})
    end,
})
